spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunoleonel/microservices-springcloud
          search-paths:
          - config-repository
server:
  port: 8080